# Generated by Django 5.2.11 on 2026-02-25 01:36

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('innovation', 'Innovation Hub'), ('indigenous', 'Indigenous Knowledge'), ('training', 'Training & Fellowship'), ('community', 'Community Action')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(max_length=300)),
                ('featured_image', models.ImageField(upload_to='work/categories/')),
                ('icon', models.ImageField(upload_to='work/icons/')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('person_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('story', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='stories/')),
                ('video_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='our_work.workcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('eligibility', models.TextField(blank=True)),
                ('application_link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='our_work.workcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas', to='our_work.workcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
