# Generated by Django 5.2.11 on 2026-02-25 03:01

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    WorkCategory = apps.get_model('our_work', 'WorkCategory')
    
    categories = [
        {
            'title': 'Innovation Hub',
            'slug': 'innovation-hub',
            'summary': 'Supporting climate enterprises and scalable green technologies grounded in local realities',
            'category_type': 'innovation',
            'icon': '🔬',
        },
        {
            'title': 'Indigenous Knowledge',
            'slug': 'indigenous-knowledge',
            'summary': 'Documenting, preserving, and revitalizing traditional ecological systems',
            'category_type': 'indigenous',
            'icon': '🌿',
        },
        {
            'title': 'Training & Fellowship',
            'slug': 'training-fellowship',
            'summary': 'Building the next generation of climate leaders through training, mentorship, and applied learning',
            'category_type': 'training',
            'icon': '📚',
        },
        {
            'title': 'Community Action',
            'slug': 'community-action',
            'summary': 'Partnering with counties and communities to co-design and implement locally led climate solutions',
            'category_type': 'community',
            'icon': '🤝',
        },
    ]
    
    for cat_data in categories:
        WorkCategory.objects.get_or_create(
            slug=cat_data['slug'],
            defaults=cat_data
        )

def remove_initial_categories(apps, schema_editor):
    WorkCategory = apps.get_model('our_work', 'WorkCategory')
    slugs = ['innovation-hub', 'indigenous-knowledge', 'training-fellowship', 'community-action']
    WorkCategory.objects.filter(slug__in=slugs).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]