# Generated by Django 5.2.11 on 2026-02-25 01:28

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('toolkit', 'Climate Toolkit'), ('research', 'Research Paper'), ('policy', 'Policy Brief'), ('indigenous', 'Indigenous Knowledge Publication'), ('manual', 'Training Manual'), ('funding', 'Funding Opportunity'), ('data', 'Climate Data Resource')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('file', models.FileField(blank=True, upload_to='resources/')),
                ('external_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='resources/covers/')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('published_date', models.DateField()),
                ('language', models.CharField(default='English', max_length=50)),
                ('download_count', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('resource_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.resourcetype')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
