# Generated by Django 5.2.11 on 2026-02-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Youth-Led. Community-Driven. Climate Solutions for Kenya.', max_length=200)),
                ('subheading', models.TextField(default='We incubate climate innovations, preserve indigenous knowledge...', max_length=500)),
                ('primary_cta_text', models.CharField(default='Join the Movement', max_length=50)),
                ('secondary_cta_text', models.CharField(default='Partner with Us', max_length=50)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('suffix', models.CharField(blank=True, default='+', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('lab', 'Innovation Lab'), ('heritage', 'Indigenous Knowledge'), ('training', 'Training'), ('community', 'Community Action')], max_length=20)),
                ('icon_image', models.ImageField(blank=True, upload_to='pillars/')),
                ('link', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
