# Generated by Django 5.2.11 on 2026-02-25 01:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(unique=True)),
                ('summary', tinymce.models.HTMLField()),
                ('pdf_file', models.FileField(upload_to='reports/')),
                ('cover_image', models.ImageField(upload_to='reports/covers/')),
                ('featured', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('challenge', tinymce.models.HTMLField()),
                ('solution', tinymce.models.HTMLField()),
                ('impact', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='case-studies/')),
                ('video_url', models.URLField(blank=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('youth', 'Youth & Farmers Trained'), ('enterprise', 'Enterprises Launched'), ('emissions', 'Emissions Reduced (tCO2e)'), ('land', 'Land Restored (acres)'), ('households', 'Households Reached'), ('indigenous', 'Indigenous Practices Documented'), ('jobs', 'Jobs Created'), ('trees', 'Trees Planted')], max_length=20, unique=True)),
                ('current_value', models.IntegerField()),
                ('target_value', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='#10B981', max_length=20)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('innovation', 'Innovation Hub'), ('restoration', 'Ecosystem Restoration'), ('water', 'Water Harvesting'), ('training', 'Training Site'), ('seed_bank', 'Community Seed Bank')], max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project-locations/')),
                ('beneficiaries', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('person_role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('video_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
